# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49fbe8bfe588a878623e9a11fc65047247be989ca3eb399f5b7cc0ebe8ab09d4c0de67c40979b97605a335dcd4afa98623f3a10d3f0b5cafbec689d88bacb833

test:
  secret_key_base: 8d4f17e30bc71aa091a035e0f6445733bf26cf7e1219fcc16285a5f56db9befa26faa00e71726ad99ebab779718b93a755ddb8be3a788f6ee03f4b7b3551e68d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
